version: '3'

services:
  owncloud:
    image: stevehendrikse/malwarelabowncloud:4.0
    ports:
      - 80:80
    expose:
      - 80
    environment:
      EXTERNAL_IP: ${EXT_IP}
      EXTRA_IP: 172.16.10.132
    volumes:
      - '${HOME}/malwarelab:/mnt/data/files:cached'
  
  jupyter:
    image: stevehendrikse/malwarelabjupyter:4.0
    ports:
      - 8000:8888
    expose:
      - 8000
    links:
      - owncloud

